### ISSUE TITLE
Build failure on linux

### ISSUE THREAD

**Issue by jteeuwen** [olebedev/go-duktape#1]
Running `go get` or `go build` on this package fails with a bunch of 'undefined reference' errors for the math lib:

	....
	./duk_bi_math.c:209: undefined reference to `atan'
	/tmp/go-build878904650/github.com/olebedev/go-duktape/_obj/duktape.o: In function `duk__asin':
	./duk_bi_math.c:206: undefined reference to `asin'
	/tmp/go-build878904650/github.com/olebedev/go-duktape/_obj/duktape.o: In function `duk__acos':
	./duk_bi_math.c:203: undefined reference to `acos'
	/tmp/go-build878904650/github.com/olebedev/go-duktape/_obj/duktape.o: In function `duk__round_fixed':
	./duk_bi_math.c:127: undefined reference to `floor'
	/tmp/go-build878904650/github.com/olebedev/go-duktape/_obj/duktape.o: In function `duk_js_compare_helper':
	./duk_js_ops.c:774: undefined reference to `__fpclassify'
	....

This is fixed by changing the C comment header in `duktape.go` to the following:

    /*
    #cgo linux LDFLAGS: -lm
    
    # include "duktape.h"
    extern duk_ret_t goFuncCall(duk_context *ctx);
    extern duk_ret_t testFunc(duk_context *ctx);
    */
    import "C"

**Comment by jteeuwen** [comment]
I have a fix for this waiting in a PR. I can submit it when my other PR is handled.

**Comment by olebedev** [comment]
First PR merged, please, send second one.

**Comment by olebedev** [comment]
PR #3 merged.
