### ISSUE TITLE
Registering native go functions and instances in duktape

### ISSUE THREAD

**Issue by mcuadros** [olebedev/go-duktape#11]
I am working on a small project and I wish to register native go functions or instances on duktape, without write code. 

This is a small example:
```go
package main

import (
	"fmt"

	"github.com/mcuadros/tba"
	"github.com/olebedev/go-duktape"
)

func main() {
	ctx := duktape.NewContext()
	tba.RegisterFunc(ctx, multiply)
	tba.RegisterFunc(ctx, sprintf)
	tba.RegisterObject(ctx, "console", &Log{})

	ctx.EvalFile("js.js")
}

func multiply(a, b int) int {
	return a * b
}

func sprintf(format string, str ...interface{}) string {
	return fmt.Sprintf(format, str...)
}

type Log struct{}

func (l *Log) Log(str ...interface{}) {
	fmt.Println(str...)
}
```

```js
a = 42
b = 5

console.log(sprintf("%d x %d = %d\n", a, b, multiply(a, b)))
//42 x 5 = 210
````

If you find this interesting to be merged on the main project I can make a PR with it.

BTW thanks for this great project.

**Comment by olebedev** [comment]
Hi @cuadros! 
Sure, it looks good.

But it seems to me go function definition should be radically changed. Now it's naive not thread safety implementation. As  I know @dckc have good solution in his fork. I've been waiting all time for his PR. Maybe it's time to cherry pick it. Anyway, I think it's better to bring syntax sugar after refactoring.

Thanks for using this project! Stay tuned.

**Comment by mcuadros** [comment]
Hey thanks!

I will keep working on it, because I need it for my own project, the changes from @dckc are really interesting but doesn't affect to my code, since the API is exactly the same.

BTW will be great if the @dckc fork can be merged or applied to the master. 

I will sent you a PR asap as I get a decent implementation.

**Comment by dckc** [comment]
Yeah, I haven't managed to get around to this in a long time.

The problem with my branch is that it has 3 unrelated changes all rolled into one. Feel free to cherrypick, of course.

**Comment by olebedev** [comment]
Hi @mcuadros!
There is good news, function definition was refactored here https://github.com/olebedev/go-duktape/commit/a2308caaa94bd19d866756c778b1b48f688be271. Please, send your PR.

**Comment by mcuadros** [comment]
Sure, but still is working in progress. Is getting bigger and bigger:
https://github.com/mcuadros/tba/blob/master/engine/duktape/register.go

Please take a look to test to see what kind of thinks you can make with my changes:
https://github.com/mcuadros/tba/blob/master/engine/duktape/register_test.go

If you can send comment over my repository will be great.
Now I am improving the struct instances push.
