### ISSUE TITLE
Use gopkg.in to keep stable packages

### ISSUE THREAD

**Issue by mcuadros** [olebedev/go-duktape#16]
I wish suggest the usage of [gopkg.in](http://labix.org/gopkg.in), and bump some version to freeze the API by versions.

BTW: I wish suggest also use gocheck, I will be glad to make a PR changing the test to gocheck.

**Comment by olebedev** [comment]
Gopkg is quite good solution, one of many. But it seems to me that revision's lockup tools like godeps(or like [this one](https://github.com/olebedev/srlt)) is more flexible. At least this approach has one vendor lock(github) instead two, in case with gopkg(github & gopkg). Also in case with gopkg you can't use development version of a package. It affects at workflow explicitly.
I think it's time to start tag versions, BTW.

**Comment by olebedev** [comment]
It's looks reasonable to use gocheck. Thank you for your submission!

**Comment by mcuadros** [comment]
@olebedev not is a constraint, just making tags you let to the people use gopkg.in (as I), this is the only requirement.

**Comment by mcuadros** [comment]
Then if you think is ok I will submit a version of the tests using gocheck
