### ISSUE TITLE
can update duktape 1.3.0 ??

### ISSUE THREAD

**Issue by zeropool** [olebedev/go-duktape#26]
duktape 1.3.0 support bytecode dump, This is a very useful function

**Comment by olebedev** [comment]
It make sense. I'll do it soon

**Comment by olebedev** [comment]
I have just created the [duktape-1.3](https://github.com/olebedev/go-duktape/tree/duktape-1.3) branch. @zeropool would you give me a hand?

**Comment by buger** [comment]
I opened PR https://github.com/olebedev/go-duktape/pull/27

**Comment by olebedev** [comment]
@zeropool @buger PTAL #28
