### ISSUE TITLE
Possible race condition in *ctxIndex.add

### ISSUE THREAD

**Issue by nkovacs** [olebedev/go-duktape#36]
Hi
I think there's a race condition in this code: https://github.com/olebedev/go-duktape/commit/e34c936bec4c4eac8a36df3f46fd2bab3a27dca2#diff-76b38c23563ff2a850abc6310d0c2739R267

It goes like this:

1. Two goroutines call `*ctxIndex.add` with the same `*Context` value.
2. Both acquire a read lock, and both fail to find the value in the map.
3. Both release the read lock.
4. Both malloc a C pointer.
5. Both attempt to acquire a write lock. Goroutine A succeeds, goroutine B blocks.
6. Goroutine A inserts the `*Context` into the map once and unlocks.
7. Goroutine B acquires the write lock.
8. Goroutine B inserts the `*Context` into the map with a different key and unlocks.

The fix is to check again if the context exists in the map after acquiring the write lock.

I may be wrong, I haven't actually used this library, I was only looking for how others solved the go 1.6 runtime pointer checks when I noticed this.

**Comment by olebedev** [comment]
Hi @nkovacs, 
agree, there is a race condition. I missed it, need to be fixed.
