### ISSUE TITLE
EvalString and company crash go on javascript errors

### ISSUE THREAD

**Issue by dckc** [olebedev/go-duktape#6]
For example:

```{go}
  ctx := duktape.NewContext()
  ctx.EvalString(`2 +**** 3`)
```

crashes:

```
FATAL 56: uncaught error
PANIC 56: uncaught error (calling abort)
SIGABRT: abort
```

I suggest only the protected variants (`PevalString` etc.) should be in the safe go API.

**Comment by olebedev** [comment]
I think that it is better to give access to all the api as possible. This defines the quality of the library. A developer himself can decide which method to use. And the code's deletion is absolutely unacceptable.  

The behavior you describe is fully documented [here](http://duktape.org/api.html#duk_peval).
