### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by lox** [olebedev/go-duktape#7]
I'm working on some code to make integrating go-duktape and js code easier at https://github.com/lox/go-servejs.

I'm creating an entirely new duktape context on each http request, and exposing JS functions to interact with the golang http.ResponseWriter. 

After the second request, it looks to me like the go funcs aren't being bound any more. Any ideas?

```
 ~/.go/src/github.com/lox/go-servejs/ on master ∆ › go test -run=NONE -bench=. -v
BenchmarkHelloWorldExample	2015/02/19 13:48:11 serving context &servejs.jsContext{ctx:(*duktape.Context)(0xc20804a078)}
2015/02/19 13:48:11 waiting for js to call end
2015/02/19 13:48:11 evaluating app js
2015/02/19 13:48:11 called __goWrite
2015/02/19 13:48:11 called __goEnd
2015/02/19 13:48:11 body: Hello World
2015/02/19 13:48:11 serving context &servejs.jsContext{ctx:(*duktape.Context)(0xc20804a0d8)}
2015/02/19 13:48:11 waiting for js to call end
2015/02/19 13:48:11 evaluating app js
2015/02/19 13:48:11 called __goWrite
2015/02/19 13:48:11 called __goEnd
2015/02/19 13:48:11 body: Hello World
2015/02/19 13:48:11 serving context &servejs.jsContext{ctx:(*duktape.Context)(0xc20804a168)}
2015/02/19 13:48:11 waiting for js to call end
2015/02/19 13:48:11 evaluating app js
2015/02/19 13:48:12 body: timed out waiting for response from js
--- FAIL: BenchmarkHelloWorldExample
	handler_test.go:37: Got status 500 Internal Server Error, expected OK
ok  	github.com/lox/go-servejs	1.098s
```

**Comment by olebedev** [comment]
I see that you don't use DestroyHeap method. But still create a context on every request is quite expensive, I think. Actually I have an example of usage, check [this](https://github.com/olebedev/go-react-example) out. There is pool of duktape contexts.
Please, let me know about your progress.

**Comment by lox** [comment]
Thanks, I saw that. Is there a way to re-use contexts between requests? I'd love a clone method :)

**Comment by olebedev** [comment]
@lox I have just reviewed your current master brunch and don't see no any test files. But I saw that you moved to pool of duktape contexts. Is the problem still there? 

BTW, you code is outdated.  API was a bit changed.
