### ISSUE TITLE
How do you access a variable or function once the script has been through browsify or webpack?

### ISSUE THREAD

**Issue by 01AutoMonkey** [olebedev/go-duktape#9]
If I have something like:

```js
function line(line) {
    return line+"ADDED STRING";
}
```

I can access it alright with go-ducktape, but if it's part of a browsify or webpack build I can no longer access it and get:

`ReferenceError: identifier 'line' undefined`

It's probably due to a scope issue, that is I think browsify for example encloses all my code in an anonymous function, but if that's the case, what's the best way to deal with that?

Example go-duktape code:

```go
  bundle, _ := readBundle("./client/build/assets/js/bundle.js")

  ctx := duktape.NewContext()
  if ctx.PevalString(string(bundle)) == 1 {
    panic(ctx.SafeToString(-1))
  }
  ctx.PevalString(`line("test...")`)
  result := ctx.SafeToString(-1)
  ctx.Pop()
  fmt.Println(result)
```

**Comment by olebedev** [comment]
Of course it browserify issue.

The short answer is:
define self object before your bundle execution
```go
ctx.EvalString(`var self = {};`)
```
then export your reference as `global`'s property
```javascript
var myModule = global.myModule = require('./myModule');
```
compile it via browserify and eval the bundle
```go
if ctx.PevalString(string(bundle)) == 1 {
  panic(ctx.SafeToString(-1))
}
```
So, now you have access to you module as `self.myModule`

```go
if ctx.PevalString(`self.myModule.doSomeWork()`) == 1 {
  panic(ctx.SafeToString(-1))
}
```

Please take a look for [this](https://github.com/olebedev/go-react-example) project. There is [similar case](https://github.com/olebedev/go-react-example/blob/master/react.go#L47).
